apps/login/urls.py
from django.conf.urls import url, include
from . import views
# from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name='login_index'),
    # url(r'^success$', views.success, name='login_success'),
    url(r'^process$', views.process, name='login_process'),
    url(r'^login$', views.login, name='login_login'),
    url(r'^logout$', views.logout, name='login_logout')
]

dojo_secrets/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^secret/', include('apps.secret.urls', namespace='secret'))
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime, timedelta
import bcrypt, re

# Create your models here.
class UserManager(models.Manager):
    def validate(self, postData):
        errors = []     # array of error messages
        if len(postData["first_name"]) == 0:
            # if first name has not been entered
            errors.append("Please enter a first name.")
        elif len(postData["first_name"]) < 2:
            errors.append("First name must be between 2-45 characters.")
        elif not re.search(r'^[A-Za-z]+$', postData["first_name"]):
            errors.append("First name must be letters only.")
        if len(postData["last_name"]) == 0:
            errors.append("Please enter a last name.")
        elif len(postData["last_name"]) < 2:
            errors.append("Last name must be between 2-45 characters.")
        elif not re.search(r'^[A-Za-z]+$', postData["last_name"]):
            errors.append("Last name must be letters only.")
        if len(postData["email"]) == 0:
            errors.append("Please enter an email address.")
        elif not re.search(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]+$', postData["email"]):
            errors.append("Invalid email address.")
        elif len(User.objects.filter(email=postData["email"])) > 0:
            # if list of users w/ this email is empty
            errors.append("Email address is already registered.")
        try:
            dob = datetime.strptime(postData["dob"], "%m/%d/%Y")
        except ValueError:
            errors.append("Invalid date of birth entered. Use M/D/YYYY format.")
        else:
            if datetime.now() < dob:
                errors.append("Future date of birth entered.")
        if len(postData["password"]) < 8:
            errors.append("Password must be 8 or more characters.")
        if postData["confirm"] != postData["password"]:
            errors.append("Passwords do not match.")
        if len(errors) == 0:
            try:
                user = User.objects.create(first_name=postData["first_name"], last_name=postData["last_name"],email=postData["email"],dob=dob,pw_hash=bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt()))
            except OverflowError:
                # Encountered an error when attempting to input 1/1/1900 as date of birth
                errors.append("Invalid date of birth.")
                return (False, errors)
            return (True, user)
            # returns (success code, user object)
        else:
            return (False, errors)
            # returns (failure, error list)

    def authenticate(self, postData):
        if "email" in postData and "password" in postData:
            try:
                user = User.objects.get(email=postData["email"])
            except User.DoesNotExist:
                return (False, "Invalid email/password combination.")
            pw_match = bcrypt.hashpw(postData['password'].encode(),user.pw_hash.encode())
            if pw_match:
                return (True, user)
            else:
                return (False, "Invalid email/password combination.")
        else:
            return (False, "Please enter login info.")


class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    dob = models.DateTimeField()
    pw_hash = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User

# Create your views here.
def index(request):
    if "id" in request.session:
        return redirect(reverse('secret:secret_index'))
    return render(request, 'login/index.html')

def success(request):
    if "id" not in request.session:
        return redirect('/')
    try:
        user = User.objects.get(id=request.session["id"])
    except User.DoesNotExist:
        messages.add_message(request, messages.INFO, "User not found.")
        return redirect('/')
    return render(request, reverse('secret:secret_index'), {"user":user})

def process(request):
    if request.method != 'POST':
        return redirect('/')
    else:
        user_valid = User.objects.validate(request.POST)
        if user_valid[0] == True:
            request.session["id"] = user_valid[1].id
            return redirect(reverse('secret:secret_index'))
        else:
            for msg in user_valid[1]:
                messages.add_message(request, messages.INFO, msg)
            return redirect('/')

def login(request):
    if request.method != 'POST':
        return redirect('/')
    else:
        user = User.objects.authenticate(request.POST)
        if user[0] == True:
            request.session["id"] = user[1].id
            return redirect(reverse('secret:secret_index'))
        else:
            messages.add_message(request, messages.INFO, user[1])
            return redirect('/')

def logout(request):
    if "id" in request.session:
        request.session.pop("id")
    return redirect('/')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dojo Secrets</title>
    {%load staticfiles%}
    <link rel="stylesheet" type="text/css" href="{%static 'login/css/main.css'%}">
  </head>
  <body>
    {%if messages%}
    <ul>
      {%for msg in messages%}
      <li>{{msg}}</li>
      {%endfor%}
    </ul>
    {%endif%}
    <div class='register'>
      <h2>Registration</h2>
      <form action='{%url 'login:login_process'%}' method='post'>
        {%csrf_token%}
        <table>
          <tbody>
            <tr>
              <td>First Name:</td>
              <td><input type='text' name='first_name'/></td>
            </tr>
            <tr>
              <td>Last Name:</td>
              <td><input type='text' name='last_name'/></td>
            </tr>
            <tr>
              <td>Email:</td>
              <td><input type='text' name='email'/></td>
            </tr>
            <tr>
              <td>Date of Birth:</td>
              <td><input type='text' name='dob'/></td>
            </tr>
            <tr>
              <td>Password:</td>
              <td><input type='password' name='password'/></td>
              <!-- <td><input type='text' name='password' default=''/></td> -->
            </tr>
            <tr>
              <td>Confirm Pw:</td>
              <td><input type='password' name='confirm'/></td>
              <!-- <td><input type='text' name='confirm' default=''/></td> -->
            </tr>
            <tr>
              <td></td>
              <td>
                <input type='submit' class='button' value='Register'/>
              </td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
    <div class='login'>
      <h2>Login</h2>
      <form action='{%url 'login:login_login'%}' method='post'>
        {%csrf_token%}
        <table>
          <tbody>
            <tr>
              <td>Email:</td>
              <td><input type='text' name='email'/></td>
            </tr>
            <tr>
              <td>Password:</td>
              <td><input type='password' name='password'/></td>
              <!-- <td><input type='text' name='password' default=''/></td> -->
            </tr>
            <tr>
              <td></td>
              <td>
                <input type='submit' class='button' value='Login'/>
              </td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
  </body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success</title>
  </head>
  <body>
    <p>Welcome {{user.first_name}}</p>
    <a href='/logout'>Log out</a>
  </body>
</html>